### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by neeraj-lad** [prodicus/spaceShooter#7]
Ubuntu 14.04 32-bit

I got this error when I tried to run the binary:
bash: ./spaceShooter: cannot execute binary file: Exec format error

I guess this is because the game was designed for a 64-bit machine, and can't be executed on a 32-bit machine. 

Could you update the README file to indicate this?

**Comment by prodicus** [comment]
Hey @neeraj-lad 

Can you confirm that you made the file executable? If not do so by 

```bash
$ chmod +x <spaceshooter_exectutable_file>
$ ./<spaceshooter_exectutable_file>   
```
Thanks for your time :smile:

**Comment by neeraj-lad** [comment]
Yes, I did.

**Comment by prodicus** [comment]
Will update the `README` shortly. Thanks for trying it out. 

Sad that you couldn't play it though :open_mouth:

**Comment by neeraj-lad** [comment]
No problem. Great job though :D
Keep it up :+1:

**Comment by prodicus** [comment]
@neeraj-lad That was kind of you. Thanks by the way :smile:
